version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.14

    working_directory: ~/project

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
      - run:
          name: install dependencies
          command: |
            pip install virtualenv
            virtualenv ENV
            . ENV/bin/activate
      - save_cache:
          paths:
            - ./ENV
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: build
          command: |
            . ENV/bin/activate
            cd Module_system\ 1.171
            ./build_module.sh

      - store_artifacts:
          path: ./build
